import React, { useEffect, useState } from "react";
import { Check, X } from "lucide-react";
import { Loader } from "@/components/shared/Bits";
import { api, formatApiError } from "@/lib/api";
import { toast } from "sonner";
import { Header, Card, Empty, useGet, inputClass, money, dateText } from "./OwnerShared";

export function RevenueCommission() {
  const [data] = useGet("/admin/nexora/revenue"); if (!data) return <Loader label="Loading revenue" />; const total = data.total_paying_shops || 0;
  return <><Header title="Revenue & Commission">Subscription revenue plus marketplace commission reporting.</Header><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Card label="Subscription revenue" value={money(data.total_subscription_revenue)} /><Card label="Paying shops" value={data.total_paying_shops} tone="sky" /><Card label="Avg / shop" value={money(data.avg_revenue_per_shop)} /><Card label="Paid order volume" value={money(data.paid_order_volume)} /><Card label={`Commission ${data.commission_percent}%`} value={money(data.estimated_commission)} /></div><div className="mt-6 grid gap-4 md:grid-cols-3">{(data.distribution || []).map((d) => { const pct = total ? Math.round((d.shop_count / total) * 100) : 0; return <div key={d.plan} className="rounded-2xl border border-slate-200 bg-white p-5"><span className="rounded-full bg-teal-50 px-2.5 py-1 text-[11px] font-bold uppercase text-teal-700">{d.plan}</span><div className="mt-3 text-2xl font-extrabold text-slate-800">{d.shop_count} sellers</div><p className="text-sm text-slate-500">{pct}% of paying shops</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-teal-500" style={{ width: `${pct}%` }} /></div><p className="mt-3 font-bold text-teal-700">{money(d.total_revenue)} revenue</p></div>; })}</div></>;
}

export function BuyersCustomers() {
  const [data] = useGet("/admin/customers"); const [selected, setSelected] = useState(null); if (!data) return <Loader label="Loading buyers" />;
  const purchases = async (c) => { try { const { data: orders } = await api.get(`/admin/customers/${c.id}/orders`); setSelected({ customer: c, orders }); } catch (e) { toast.error(formatApiError(e)); } };
  return <><Header title="Buyers / Customers">Customer accounts, order count and total spending.</Header><div className="grid gap-6 xl:grid-cols-[1fr_380px]"><div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase text-slate-500"><tr><th className="p-4">Customer</th><th>Orders</th><th>Spent</th><th></th></tr></thead><tbody>{data.map((c) => <tr key={c.id} className="border-t border-slate-100"><td className="p-4"><b>{c.name}</b><small className="block text-slate-400">{c.email}</small></td><td>{c.order_count}</td><td>{money(c.total_spent_bdt)}</td><td><button onClick={() => purchases(c)} className="rounded-lg border px-3 py-2 text-xs font-bold">Purchases</button></td></tr>)}</tbody></table></div><aside className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold text-slate-800">Purchase history</h2>{selected ? <div className="mt-3"><p className="font-semibold">{selected.customer.name}</p>{selected.orders.map((o) => <div key={o.id} className="mt-3 rounded-xl bg-slate-50 p-3 text-sm"><b>{o.id}</b><span className="float-right">{money(o.total)}</span><small className="mt-1 block capitalize text-slate-400">{o.status} · {dateText(o.created_at)}</small></div>)}{!selected.orders.length && <Empty />}</div> : <p className="mt-3 text-sm text-slate-400">Choose a customer.</p>}</aside></div></>;
}

export function PendingConfirmations() {
  const [rows, load] = useGet("/admin/nexora/pending"); const [rejecting, setRejecting] = useState(null); const [reason, setReason] = useState(""); if (!rows) return <Loader label="Loading pending confirmations" />;
  const pending = rows.filter((r) => ["pending", "pending_payment"].includes(r.status)); const reviewed = rows.filter((r) => r.status === "rejected");
  const confirm = async (r) => { try { await api.patch(`/admin/nexora/pending/${r.id}/confirm`); toast.success("Subscription confirmed & shop activated"); load(); } catch (e) { toast.error(formatApiError(e)); } };
  const reject = async (r) => { if (!reason.trim()) return toast.error("Enter a rejection reason"); try { await api.patch(`/admin/nexora/pending/${r.id}/reject`, { reason }); toast.success("Subscription rejected"); setRejecting(null); setReason(""); load(); } catch (e) { toast.error(formatApiError(e)); } };
  return <><Header title="Pending Confirmations">Seller subscriptions waiting for owner review.</Header><div className="space-y-4">{pending.map((r) => <article key={r.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-col justify-between gap-4 lg:flex-row"><div><div className="flex flex-wrap items-center gap-2"><b className="text-slate-800">{r.shop_name}</b><span className="rounded-full bg-teal-50 px-2 py-1 text-[10px] font-bold uppercase text-teal-700">{r.plan}</span></div><div className="mt-2 grid gap-1 text-sm text-slate-500 sm:grid-cols-2"><span>👤 {r.owner_name}</span><span>📞 {r.phone || "—"}</span><span>✉️ {r.email}</span><span>💳 {r.payment_method || "—"} · {money(r.amount_paid)}</span><span>🔑 TxID: {r.transaction_id || "—"}</span></div></div>{rejecting === r.id ? <div className="min-w-[260px]"><textarea value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Reason for rejection..." className={`${inputClass} h-20 resize-none`} /><div className="mt-2 flex gap-2"><button onClick={() => reject(r)} className="rounded-lg bg-rose-600 px-3 py-2 text-xs font-bold text-white">Confirm reject</button><button onClick={() => setRejecting(null)} className="rounded-lg border px-3 py-2 text-xs font-bold">Cancel</button></div></div> : <div className="flex gap-2"><button onClick={() => confirm(r)} className="inline-flex items-center gap-1 rounded-xl bg-teal-600 px-4 py-2.5 text-xs font-bold text-white"><Check size={14} /> Confirm & Activate</button><button onClick={() => setRejecting(r.id)} className="inline-flex items-center gap-1 rounded-xl border border-rose-200 px-4 py-2.5 text-xs font-bold text-rose-600"><X size={14} /> Reject</button></div>}</div></article>)}{!pending.length && <Empty>No pending confirmations 🎉</Empty>}</div>{!!reviewed.length && <><h2 className="mb-3 mt-8 font-bold text-slate-600">Recently rejected</h2><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white">{reviewed.map((r) => <div key={r.id} className="border-t border-slate-100 p-4 text-sm first:border-0"><b>{r.shop_name}</b> · {r.owner_name}<span className="float-right rounded-full bg-rose-50 px-2.5 py-1 text-xs font-bold text-rose-600">Rejected</span><small className="mt-1 block text-slate-400">{r.rejected_reason}</small></div>)}</div></>}</>;
}

export function AddSubscription() {
  const [shops] = useGet("/admin/nexora/shops"); const [settings] = useGet("/admin/platform-settings");
  const today = new Date().toISOString().slice(0, 10); const plus30 = new Date(Date.now() + 30 * 86400000).toISOString().slice(0, 10);
  const [form, setForm] = useState({ shop_id: "", plan: "start", amount_paid: 500, payment_method: "bkash", transaction_id: "", started_at: today, expires_at: plus30 });
  if (!shops || !settings) return <Loader label="Loading shops" />;
  const prices = { start: Number(settings.plans?.start?.price_bdt ?? 500), grow: Number(settings.plans?.grow?.price_bdt ?? 1500), pro: Number(settings.plans?.pro?.price_bdt ?? 3000) };
  const save = async () => { try { if (!form.shop_id) return toast.error("Select a shop"); await api.post("/admin/nexora/subscriptions", { ...form, amount_paid: Number(form.amount_paid), started_at: `${form.started_at}T00:00:00+00:00`, expires_at: `${form.expires_at}T23:59:59+00:00` }); toast.success("Subscription added & shop activated"); } catch (e) { toast.error(formatApiError(e)); } };
  const startChanged = (v) => { const d = new Date(`${v}T00:00:00`); d.setDate(d.getDate() + 30); setForm({ ...form, started_at: v, expires_at: d.toISOString().slice(0, 10) }); };
  return <><Header title="Add Subscription">Manually record a plan purchase after you confirm payment.</Header><section className="max-w-xl rounded-2xl border border-slate-200 bg-white p-6"><div className="space-y-4"><label className="block text-xs font-bold text-slate-500">SHOP<select value={form.shop_id} onChange={(e) => setForm({ ...form, shop_id: e.target.value })} className={`mt-1 ${inputClass}`}><option value="">— Select a shop —</option>{shops.map((s) => <option key={s.id} value={s.id}>{s.name} {s.plan ? `(${s.plan.toUpperCase()})` : ""}</option>)}</select></label><div><p className="mb-2 text-xs font-bold text-slate-500">PLAN</p><div className="flex gap-2">{["start", "grow", "pro"].map((p) => <button key={p} onClick={() => setForm({ ...form, plan: p, amount_paid: prices[p] })} className={`flex-1 rounded-xl border-2 py-2.5 text-sm font-bold ${form.plan === p ? "border-teal-500 bg-teal-50 text-teal-700" : "border-slate-200 text-slate-500"}`}>{p.toUpperCase()}</button>)}</div></div><label className="block text-xs font-bold text-slate-500">AMOUNT PAID (BDT)<input type="number" min="0" value={form.amount_paid} onChange={(e) => setForm({ ...form, amount_paid: e.target.value })} className={`mt-1 ${inputClass}`} /></label><label className="block text-xs font-bold text-slate-500">PAYMENT METHOD<select value={form.payment_method} onChange={(e) => setForm({ ...form, payment_method: e.target.value })} className={`mt-1 ${inputClass}`}><option value="bkash">bKash</option><option value="nagad">Nagad</option><option value="cash">Cash</option><option value="bank">Bank</option><option value="manual">Manual</option></select></label><label className="block text-xs font-bold text-slate-500">TRANSACTION ID (OPTIONAL)<input value={form.transaction_id} onChange={(e) => setForm({ ...form, transaction_id: e.target.value })} className={`mt-1 ${inputClass}`} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-slate-500">JOIN DATE<input type="date" value={form.started_at} onChange={(e) => startChanged(e.target.value)} className={`mt-1 ${inputClass}`} /></label><label className="text-xs font-bold text-slate-500">EXPIRY DATE<input type="date" value={form.expires_at} onChange={(e) => setForm({ ...form, expires_at: e.target.value })} className={`mt-1 ${inputClass}`} /></label></div><button onClick={save} className="w-full rounded-xl bg-teal-600 py-3 text-sm font-bold text-white">Add subscription & activate shop</button></div></section></>;
}

export function OwnerSettings() {
  const [data, setData] = useState(null); useEffect(() => { api.get("/admin/platform-settings").then((r) => setData(r.data)).catch((e) => toast.error(formatApiError(e))); }, []); if (!data) return <Loader label="Loading settings" />;
  const setPlan = (id, key, value) => setData((d) => ({ ...d, plans: { ...d.plans, [id]: { ...d.plans[id], [key]: value } } }));
  const save = async () => { try { const body = { commission_percent: Number(data.commission_percent), plans: data.plans, delivery: { provider: data.delivery.provider, enabled: data.delivery.enabled, api_base_url: data.delivery.api_base_url, credential_reference: data.delivery.credential_reference } }; const { data: saved } = await api.put("/admin/platform-settings", body); setData(saved); toast.success("Settings saved"); } catch (e) { toast.error(formatApiError(e)); } };
  return <><Header title="Settings">Owner-level commercial settings, plan prices and delivery adapter.</Header><section className="rounded-2xl border border-slate-200 bg-white p-6"><label className="block max-w-xs text-sm font-semibold text-slate-600">Marketplace commission (%)<input type="number" min="0" max="50" value={data.commission_percent} onChange={(e) => setData({ ...data, commission_percent: e.target.value })} className={`mt-1 ${inputClass}`} /></label><div className="mt-6 grid gap-4 md:grid-cols-3">{Object.entries(data.plans).map(([id, p]) => <div key={id} className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-400">{id}</p><input value={p.name} onChange={(e) => setPlan(id, "name", e.target.value)} className={`mt-2 ${inputClass}`} /><label className="mt-3 block text-xs font-bold text-slate-500">MONTHLY PRICE (BDT)<input type="number" value={p.price_bdt} onChange={(e) => setPlan(id, "price_bdt", Number(e.target.value))} className={`mt-1 ${inputClass}`} /></label></div>)}</div></section><section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-bold text-slate-800">Delivery provider adapter</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-xs font-bold text-slate-500">PROVIDER<input value={data.delivery.provider} onChange={(e) => setData({ ...data, delivery: { ...data.delivery, provider: e.target.value } })} className={`mt-1 ${inputClass}`} /></label><label className="text-xs font-bold text-slate-500">API BASE URL<input value={data.delivery.api_base_url} onChange={(e) => setData({ ...data, delivery: { ...data.delivery, api_base_url: e.target.value } })} className={`mt-1 ${inputClass}`} /></label><label className="text-xs font-bold text-slate-500">CREDENTIAL ENV KEY<input value={data.delivery.credential_reference} onChange={(e) => setData({ ...data, delivery: { ...data.delivery, credential_reference: e.target.value.toUpperCase() } })} className={`mt-1 ${inputClass}`} /></label><label className="flex items-center gap-2 pt-7 text-sm"><input type="checkbox" checked={data.delivery.enabled} onChange={(e) => setData({ ...data, delivery: { ...data.delivery, enabled: e.target.checked } })} /> Enable configured adapter</label></div></section><button onClick={save} className="mt-6 rounded-xl bg-teal-600 px-6 py-3 text-sm font-bold text-white">Save settings</button></>;
}
