import React, { useState } from "react";
import { Search, Upload, Pencil, Trash2 } from "lucide-react";
import { Loader } from "@/components/shared/Bits";
import { api, formatApiError } from "@/lib/api";
import { toast } from "sonner";
import { Header, Empty, useGet, inputClass, money, dateText } from "./OwnerShared";

export function SellersSubscriptions() {
  const [rows] = useGet("/admin/nexora/seller-subscriptions");
  const [search, setSearch] = useState(""); const [plan, setPlan] = useState("all");
  if (!rows) return <Loader label="Loading sellers & subscriptions" />;
  const filtered = rows.filter((r) => {
    const q = search.toLowerCase();
    const match = !q || [r.shop_name, r.seller_name, r.email, r.phone].some((v) => String(v || "").toLowerCase().includes(q));
    return match && (plan === "all" || r.plan === plan);
  });
  const badge = (r) => {
    if (r.subscription_status === "rejected") return ["Rejected", "bg-rose-50 text-rose-600"];
    if (r.subscription_status === "expired" || (r.days_remaining != null && r.days_remaining < 0)) return ["Expired", "bg-rose-50 text-rose-600"];
    if (r.days_remaining != null && r.days_remaining <= 5) return ["Expiring soon", "bg-amber-50 text-amber-700"];
    if (["active", "active_dev"].includes(r.subscription_status)) return ["Active", "bg-emerald-50 text-emerald-700"];
    return [r.subscription_status || "No subscription", "bg-slate-100 text-slate-500"];
  };
  return <><Header title="Sellers & Subscriptions">Every shop's plan, payment, status and renewal date.</Header>
    <div className="mb-5 flex flex-wrap gap-3"><div className="relative max-w-sm flex-1"><Search size={16} className="absolute left-3 top-3 text-slate-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search shop, owner, phone..." className={`${inputClass} pl-9`} /></div><select value={plan} onChange={(e) => setPlan(e.target.value)} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm"><option value="all">All plans</option><option value="start">START</option><option value="grow">GROW</option><option value="pro">PRO</option></select></div>
    <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase text-slate-500"><tr><th className="p-4">Shop</th><th>Owner</th><th>Plan</th><th>Paid</th><th>Start</th><th>Expiry</th><th>Days left</th><th>Status</th></tr></thead><tbody>{filtered.map((r) => { const [label, color] = badge(r); return <tr key={r.seller_id} className="border-t border-slate-100"><td className="p-4"><b>{r.shop_name || "No shop"}</b><small className="block text-slate-400">{r.shop_slug}</small></td><td>{r.seller_name}<small className="block text-slate-400">{r.phone || r.email}</small></td><td><span className="rounded-full bg-teal-50 px-2.5 py-1 text-[11px] font-bold uppercase text-teal-700">{r.plan || "—"}</span></td><td>{money(r.amount_paid)}</td><td>{dateText(r.started_at)}</td><td>{dateText(r.expires_at)}</td><td className={r.days_remaining != null && r.days_remaining <= 5 ? "font-bold text-rose-600" : ""}>{r.days_remaining == null ? "—" : `${r.days_remaining} days`}</td><td><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${color}`}>{label}</span></td></tr>; })}</tbody></table>{!filtered.length && <Empty />}</div></>;
}

const emptyCategory = { name: "", slug: "", image_url: "", theme: "fashion_editorial", icon: "tag", is_active: true };

export function CategoriesAdmin() {
  const [categories, load] = useGet("/admin/nexora/categories");
  const [form, setForm] = useState(emptyCategory); const [editing, setEditing] = useState(null); const [uploading, setUploading] = useState(false);
  if (!categories) return <Loader label="Loading categories" />;
  const save = async () => { try { if (!form.name.trim()) return toast.error("Category name is required"); editing ? await api.put(`/admin/nexora/categories/${editing}`, form) : await api.post("/admin/nexora/categories", form); toast.success(editing ? "Category updated" : "Category added"); setEditing(null); setForm(emptyCategory); load(); } catch (e) { toast.error(formatApiError(e)); } };
  const edit = (c) => { setEditing(c.id || c.slug); setForm({ name: c.name || "", slug: c.slug || "", image_url: c.image_url || "", theme: c.theme || "fashion_editorial", icon: c.icon || "tag", is_active: c.is_active !== false }); };
  const upload = async (file) => { if (!file) return; setUploading(true); try { const fd = new FormData(); fd.append("file", file); const { data } = await api.post("/upload", fd, { headers: { "Content-Type": "multipart/form-data" } }); setForm((f) => ({ ...f, image_url: data.url })); toast.success("Image uploaded"); } catch (e) { toast.error(formatApiError(e)); } finally { setUploading(false); } };
  const toggle = async (c) => { try { await api.patch(`/admin/nexora/categories/${c.id || c.slug}/status`, { is_active: !c.is_active }); load(); } catch (e) { toast.error(formatApiError(e)); } };
  const remove = async (c) => { if (!window.confirm(`Delete "${c.name}"?`)) return; try { await api.delete(`/admin/nexora/categories/${c.id || c.slug}`); toast.success("Category deleted"); load(); } catch (e) { toast.error(formatApiError(e)); } };
  return <><Header title="Categories">These control the marketplace category structure.</Header>
    <section className="mb-7 max-w-2xl rounded-2xl border border-slate-200 bg-white p-6"><h2 className="mb-4 font-bold text-slate-800">{editing ? "Edit category" : "Add a category"}</h2><div className="grid gap-4 sm:grid-cols-[120px_1fr]"><div><div className="flex h-28 w-28 items-center justify-center overflow-hidden rounded-xl border-2 border-dashed border-teal-200 bg-teal-50">{form.image_url ? <img src={form.image_url} alt="" className="h-full w-full object-cover" /> : <Upload size={22} className="text-teal-600" />}</div><label className="mt-2 block cursor-pointer text-center text-xs font-bold text-teal-700">{uploading ? "Uploading..." : "Choose image"}<input type="file" accept="image/*" className="hidden" onChange={(e) => upload(e.target.files?.[0])} /></label></div><div className="space-y-3"><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Category name" className={inputClass} /><input value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value })} placeholder="Slug (optional)" className={inputClass} /><div className="grid gap-3 sm:grid-cols-2"><input value={form.theme} onChange={(e) => setForm({ ...form, theme: e.target.value })} placeholder="Theme preset" className={inputClass} /><input value={form.icon} onChange={(e) => setForm({ ...form, icon: e.target.value })} placeholder="Icon name" className={inputClass} /></div><div className="flex gap-2"><button onClick={save} className="rounded-full bg-teal-600 px-5 py-2.5 text-sm font-bold text-white">{editing ? "Save changes" : "Add category"}</button>{editing && <button onClick={() => { setEditing(null); setForm(emptyCategory); }} className="rounded-full border px-5 py-2.5 text-sm font-semibold">Cancel</button>}</div></div></div></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{categories.map((c) => <article key={c.id || c.slug} className={`overflow-hidden rounded-2xl border border-slate-200 bg-white ${c.is_active === false ? "opacity-55" : ""}`}><div className="h-28 bg-teal-50">{c.image_url && <img src={c.image_url} alt={c.name} className="h-full w-full object-cover" />}</div><div className="p-4"><b className="text-slate-800">{c.name}</b><p className="text-xs text-slate-400">/{c.slug} · {c.product_count || 0} products</p><div className="mt-3 flex items-center justify-between"><button onClick={() => toggle(c)} className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${c.is_active === false ? "bg-slate-100 text-slate-500" : "bg-emerald-50 text-emerald-700"}`}>{c.is_active === false ? "Hidden" : "Active"}</button><div className="flex gap-2"><button onClick={() => edit(c)} className="text-teal-700"><Pencil size={15} /></button><button onClick={() => remove(c)} className="text-rose-600"><Trash2 size={15} /></button></div></div></div></article>)}</div></>;
}

export function FeaturedShops() {
  const [shops, load] = useGet("/admin/nexora/featured-shops"); const [search, setSearch] = useState("");
  if (!shops) return <Loader label="Loading shops" />;
  const filtered = shops.filter((s) => (s.shop_name || "").toLowerCase().includes(search.toLowerCase()));
  const toggle = async (s) => { try { await api.patch(`/admin/nexora/featured-shops/${s.id}`, { is_featured: !s.is_featured }); load(); } catch (e) { toast.error(formatApiError(e)); } };
  return <><Header title="Featured Shops">Manually feature shops; highly-rated shops are also marked as auto-qualified.</Header><div className="mb-5 flex items-center justify-between gap-3"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search shops..." className={`${inputClass} max-w-xs`} /><span className="text-sm text-slate-500"><b className="text-slate-800">{shops.filter((s) => s.is_featured || s.auto_qualifies).length}</b> featured/qualified</span></div><div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase text-slate-500"><tr><th className="p-4">Shop</th><th>Plan</th><th>Rating</th><th>Auto-qualified</th><th>Manually featured</th></tr></thead><tbody>{filtered.map((s) => <tr key={s.id} className="border-t border-slate-100"><td className="p-4"><b>{s.shop_name}</b><small className="block text-slate-400">/{s.slug}</small></td><td className="uppercase">{s.plan || "—"}</td><td><span className="text-amber-500">★</span> {s.rating || 0} ({s.total_reviews || 0})</td><td>{s.auto_qualifies ? <span className="font-bold text-emerald-700">Yes</span> : <span className="text-slate-300">No</span>}</td><td><button onClick={() => toggle(s)} className={`relative h-6 w-11 rounded-full ${s.is_featured ? "bg-teal-600" : "bg-slate-200"}`}><span className={`absolute top-0.5 h-5 w-5 rounded-full bg-white shadow transition-all ${s.is_featured ? "left-[22px]" : "left-0.5"}`} /></button></td></tr>)}</tbody></table>{!filtered.length && <Empty />}</div></>;
}
